name: Build jar

on:
  workflow_dispatch:
  push:
    branches:
      - huynn/deployment-preparation

permissions:
  contents: read

jobs:
  build-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Hello, ${{ github.repository_owner }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: f-pms/UI
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ui
          path: dist

  build-api:
    runs-on: ubuntu-latest
    needs: build-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: f-pms/API
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Download UI artifact
        uses: actions/download-artifact@v4
        with:
          name: ui
          path: core/core-api/src/main/resources/ui
          merge-multiple: true

      - name: List files
        run: ls -a core/core-api/src/main/resources/ui
