on:
  workflow_call:
    inputs:
      build-command:
        required: true
        type: string
      test-command:
        required: true
        type: string
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0
      - name: Git pull
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git merge origin/${{ github.head_ref }} --allow-unrelated-histories
          ls -a
      - name: Build
        run: ${{ inputs.build-command }}
      - name: Test
        run: ${{ inputs.test-command }}
