on:
  workflow_call:

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/Devops
          # TODO: change to master
          ref: huynn/linter
          fetch-depth: 0
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linters
          path: .github/linters
          overwrite: true
  ci:
    runs-on: ubuntu-latest
    needs: clone
    steps:
      - name: Lint PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          subjectPattern: ^([A-Z]).+$
          subjectPatternError: The subject "{subject}" found in the pull request title "{title}" didn't match the configured pattern. Please ensure that the subject start with an uppercase character.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0
      - name: Git merge
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git merge origin/${{ github.head_ref }} --allow-unrelated-histories
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: linters
          path: .github/linters
      - run: ls -la .github/linters
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        if: ${{ hashFiles('yarn.lock') != '' }}
      - name: Lint codebase
        id: super-linter
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: master
          FILTER_REGEX_EXCLUDE: dist/**/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_WORKSPACE: ${{ github.workspace }}
          TYPESCRIPT_ES_CONFIG_FILE: .github/linters/.eslintrc.json
          MARKDOWN_CONFIG_FILE: .github/linters/.markdown-lint.yml
          YAML_CONFIG_FILE: .github/linters/.yaml-lint.yml
          TYPESCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
