on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      dry_run:
        required: false
        type: boolean
        default: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - name: Release
        uses: zwaldowski/semver-release-action@v3
        with:
          dry_run: ${{ inputs.dry_run }}
          bump: ${{ inputs.version }}
          github_token: ${{ github.token }}
