name: Upload artifact

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0
      - name: Git merge
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git merge origin/${{ github.head_ref }} --allow-unrelated-histories
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linters-${{ github.head_ref }}
          path: .github/linters
          overwrite: true
